@rootURL = http://localhost:20772

GET {{rootURL}}/api/Product
Accept: application/json

###
GET {{rootURL}}/api/Product/1
Accept: application/json

###
POST {{rootURL}}/api/Product
Content-Type: application/json

{
  "name": "Hood",
  "brand": "Love Mountains",
  "color": "Green",
  "size": 4,
  "gender": "uni",
  "price": 250,
  "description": ""
}

###
PUT {{rootURL}}/api/Product/3
Content-Type: application/json

{
  "id": 3,
  "name": "Hood",
  "brand": "Love Mountains",
  "color": "Black",
  "size": 4,
  "gender": "uni",
  "price": 450,
  "description": ""
}

###
DELETE {{rootURL}}/api/Product/1
